### ISSUE TITLE
HexBinary string must be even length

### ISSUE THREAD

**Issue by simonwibberley** [uakihir0/kbsky#104]
Hi there,

Thanks for this library! When streaming the firehose I frequently get:

```
java.lang.IllegalArgumentException: HexBinary string must be even length
	at kotlinx.serialization.internal.InternalHexConverter.parseHexBinary(Platform.common.kt:16)
	at kotlinx.serialization.SerialFormatKt.decodeFromHexString(SerialFormat.kt:150)
	at work.socialhub.kbsky.stream.util.StreamClient.onMessage(StreamClient.kt:152)
	at work.socialhub.kbsky.stream.util.StreamClient.access$onMessage(StreamClient.kt:15)
	at work.socialhub.kbsky.stream.util.StreamClient$1.invokeSuspend(StreamClient.kt:37)
	at work.socialhub.kbsky.stream.util.StreamClient$1.invoke(StreamClient.kt)
	at work.socialhub.kbsky.stream.util.StreamClient$1.invoke(StreamClient.kt)
	at work.socialhub.khttpclient.websocket.WebsocketRequest$start$2$4$2.invokeSuspend(WebsocketRequest.kt:109)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith$$$capture(ContinuationImpl.kt:33)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:113)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:823)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707)
```

I'm running from Java 11 using Kotlin 2.0. 

Many thanks

**Comment by simonwibberley** [comment]
I've seen the comment in the source code now!

**Comment by uakihir0** [comment]
I'm closing this section as it is currently not manageable.
We are planning to support JetStream, so please consider that as well.
