### ISSUE TITLE
Question - Correct way to refresh OAuth session?

### ISSUE THREAD

**Issue by MarcFletcher** [uakihir0/kbsky#113]
Thanks for the library.

If a user has authenticated via OAuth, and the access_token has now expired, what is the expected syntax to generate a new session or access token using only the `refresh_token`?

I've tried a couple of things, this seems to be the closest:

```
    BearerTokenAuthProvider bearerTokenAuthProvider = new BearerTokenAuthProvider(refreshToken);
    AuthRequest authRequest = new AuthRequest(bearerTokenAuthProvider );
    ATProtocol instance = ATProtocolFactory.INSTANCE.instance(pdsURL);
    Response<ServerRefreshSessionResponse> serverRefreshSessionResponseResponse =
        instance.server().refreshSession(authRequest);
```

But results in:

> Exception in thread "main" work.socialhub.kbsky.ATProtocolException: Token could not be verified
> 	at work.socialhub.kbsky.internal.share._InternalUtility.handleError(_InternalUtility.kt:112)
> 	at work.socialhub.kbsky.internal.com.atproto._ServerResource.refreshSession(_ServerResource.kt:205)
> 	at org.example.Main.tryToRefreshAccessToken(Main.java:119)
> 	at org.example.Main.main(Main.java:103)

**Comment by MarcFletcher** [comment]
If I had to guess it looks like [tokenRequest](https://github.com/uakihir0/kbsky/blob/1fc67db4654cb17caefc1201862a95bbee362660/auth/src/commonMain/kotlin/work/socialhub/kbsky/auth/internal/_OAuthResource.kt#L91C5-L91C6)  needs to optional support being called with the following parameters:

grant_type = "refresh_token"
refresh_token = "ref-token"

Similar to https://github.com/bluesky-social/atproto/blob/e94f51853787bd3ab763c3719b69e70407b2b2c0/packages/oauth/oauth-client/src/oauth-server-agent.ts#L120. 

In the link there is also some validation to confirm we're contacting the correct issuer. 

If this is indeed missing is there any possibility to implement this in the snapshot version?

**Comment by uakihir0** [comment]
@MarcFletcher 
Thank you for the issue and research.
I will try to implement it!

**Comment by MarcFletcher** [comment]
Please see a PR that provides this fix here - https://github.com/uakihir0/kbsky/pull/121
